//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 03:15:40 PM ART 
//


package org.zonales.entities;

import java.util.ArrayList;


public class Posts {

    protected ArrayList<Post> post;

    public Posts() {
    }

    public Posts(ArrayList<Post> posts) {
        this.post = posts;
    }

    public ArrayList<Post> getPost() {
        return post;
    }

    public void setPost(ArrayList<Post> post) {
        this.post = post;
    }

    @Override
    public String toString() {
        return "Posts{" + "posts=" + post + '}';
    }

    


}
