#!/bin/sh

# http://www.freeos.com/guides/lsst/

#ARCH_SINONIMOS=$1
#ARCH_CONJUGADOS=$2
#PREFIJO='bloque'
#DELIMITADOR='##'
#TEMPORAL='temporal'

# separa los bloques del archivo en partes (en otros archivos)
#function separarBloques($archivo,$dir_destino)
#{
#archivo=$ARCH_SINONIMOS
#dir_destino='/home/alumnoing/g2p/workspace/bloques_conjugados'


#	mkdir $dir_destino
#	cd $dir_destino

#	csplit -s --digits=1 --prefix=$PREFIJO $archivo '/##/' '{*}'
#	nombres_archivos=`ls`

#	for archivo_actual in $nombres_archivos
#	do
#		grep -v $DELIMITADOR $archivo_actual > $TEMPORAL
#		rm -f $archivo_actual
#		mv $TEMPORAL $archivo_actual
#	done

#	cd ..
#}

#separarBloques($ARCH_SINONIMOS,'/home/alumnoing/g2p/workspace/bloques_sinonimos');

dir_conjugados='/home/alumnoing/g2p/workspace/bloques_conjugados'
dir_sinonimos='/home/alumnoing/g2p/workspace/bloques_sinonimos'
dir_unificado='/home/alumnoing/g2p/workspace/bloques_unificado'

nombres_archivos_conjugados=`ls $dir_conjugados`
nombres_archivos_sinonimos=`ls $dir_sinonimos`

for archivo_conjugado_actual in $nombres_archivos_conjugados do
	infinitivo_conjugado_actual=`grep '[a,e,i]r$' $archivo_conjugado_actual`
	
	for archivo_sinonimo_actual in $nombres_archivos_sinonimos do
		cant_coindidencias=`grep -c $infinitivo_conjugado_actual $archivo_sinonimo_actual`
		
		if [ $cant_coindidencias -ne 0]
		then
			# (queda duplicado el infinitivo)
			cat ${dir_sinonimos}/$archivo_sinonimo_actual ${dir_conjugados}/$archivo_conjugado_actual >> $dir_unificado/$id
			break;
		fi
	done
done
cat ${dir_conjugados}/$archivo_conjugado_actual > ${dir_unificado}/$id
