//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 03:15:40 PM ART 
//
package org.zonales.entities;

import java.util.ArrayList;

public class Post {

    protected String id;
    protected String docType;
    protected String source;
    protected Double postLatitude;
    protected Double postLongitude;
    protected Double sourceLatitude;
    protected Double sourceLongitude;
    protected User fromUser;
    protected ArrayList<User> toUsers;
    protected String title;
    protected String text;
    protected ArrayList<LinkType> links;
    protected ArrayList<ActionType> actions;
    protected Zone zone;
    protected String extendedString;
    protected ArrayList<String> tags;
    protected Long created;
    protected Long modified;
    protected int relevance;
    protected int relevanceDelta;
    protected String state;
    protected String verbatim;

    public Post() {
    }

    public Post(String id, String docType, String source, Double sourceLatitude, Double sourceLongitude, User fromUser, ArrayList<User> toUsers, String title, String text, ArrayList<LinkType> links, ArrayList<ActionType> actions, Zone zone, String extendedString, ArrayList<String> tags, Long created, Long modified, int relevance, int relevanceDelta, String verbatim) {
        this.id = id;
        this.docType = docType;
        this.source = source;
        this.postLatitude = sourceLatitude;
        this.postLongitude = sourceLongitude;
        this.fromUser = fromUser;
        this.toUsers = toUsers;
        this.title = title;
        this.text = text;
        this.links = links;
        this.actions = actions;
        this.zone = zone;
        this.extendedString = extendedString;
        this.tags = tags;
        this.created = created;
        this.modified = modified;
        this.relevance = relevance;
        this.relevanceDelta = relevanceDelta;
        this.verbatim = verbatim;
    }

    public Double getSourceLatitude() {
        return sourceLatitude;
    }

    public void setSourceLatitude(Double sourceLatitude) {
        this.sourceLatitude = sourceLatitude;
    }

    public Double getSourceLongitude() {
        return sourceLongitude;
    }

    public void setSourceLongitude(Double sourceLongitude) {
        this.sourceLongitude = sourceLongitude;
    }

    public ArrayList<ActionType> getActions() {
        return actions;
    }

    public void setActions(ArrayList<ActionType> actions) {
        this.actions = actions;
    }

    public Long getCreated() {
        return created;
    }

    public void setCreated(Long created) {
        this.created = created;
    }

    public User getFromUser() {
        return fromUser;
    }

    public void setFromUser(User fromUser) {
        this.fromUser = fromUser;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ArrayList<LinkType> getLinks() {
        return links;
    }

    public void setLinks(ArrayList<LinkType> links) {
        this.links = links;
    }

    public Long getModified() {
        return modified;
    }

    public void setModified(Long modified) {
        this.modified = modified;
    }

    public int getRelevance() {
        return relevance;
    }

    public void setRelevance(int relevance) {
        this.relevance = relevance;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public ArrayList<String> getTags() {
        return tags;
    }

    public void setTags(ArrayList<String> tags) {
        this.tags = tags;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ArrayList<User> getToUsers() {
        return toUsers;
    }

    public void setToUsers(ArrayList<User> toUsers) {
        this.toUsers = toUsers;
    }

    public String getVerbatim() {
        return verbatim;
    }

    public void setVerbatim(String verbatim) {
        this.verbatim = verbatim;
    }

    public Zone getZone() {
        return zone;
    }

    public void setZone(Zone zone) {
        this.zone = zone;
    }

    @Override
    public String toString() {
        return "Post{" + "source=" + source + "id=" + id + "fromUser=" + fromUser + "toUsers=" + toUsers + "title=" + title + "text=" + text + "links=" + links + "actions=" + actions + "tags=" + tags + "created=" + created + "modified=" + modified + "relevance=" + relevance + "verbatim=" + verbatim + '}';
    }

    /**
     * Get the value of state
     *
     * @return the value of state
     */
    public String getState() {
        return state;
    }

    /**
     * Set the value of state
     *
     * @param state new value of state
     */
    public void setState(String state) {
        this.state = state;
    }

    public String getDocType() {
        return docType;
    }

    public void setDocType(String docType) {
        this.docType = docType;
    }

    public int getRelevanceDelta() {
        return relevanceDelta;
    }

    public void setRelevanceDelta(int relevanceDelta) {
        this.relevanceDelta = relevanceDelta;
    }

    public String getExtendedString() {
        return extendedString;
    }

    public void setExtendedString(String extendedString) {
        this.extendedString = extendedString;
    }

    public Double getPostLatitude() {
        return postLatitude;
    }

    public void setPostLatitude(Double postLatitude) {
        this.postLatitude = postLatitude;
    }

    public Double getPostLongitude() {
        return postLongitude;
    }

    public void setPostLongitude(Double postLongitude) {
        this.postLongitude = postLongitude;
    }
}
